#!/bin/bash 

for i in lang/*; do
  lang="$(basename $i)"
  { 
    echo "#!/bin/$lang" 
    echo "settings='$(<lang/bash/.settings)'"
    cat lang/$lang/.settings lang/$lang/.util lang/$lang/.transpile 
    echo "######################### begin-of-powscript-functions"
    cd lang/$lang &>/dev/null
    echo "powfunctions=\"$(echo *)\""
    cd - &>/dev/null
    cat lang/$lang/*
    echo "######################### end-of-powscript-functions"
    cat src/powscript.$lang
  } > powscript && chmod 755 powscript
done
  
