#!/bin/bash
set -e # remove allowance errors (and exit 1)
echo -e "todo: powscript should return error code\n\n"

printline(){
  cat | awk "{ print \"$*> \"\$0 }"
}

for file in test/*.bash; do 
  [[ -x $file ]] && $file | printline $file
done

for file in test/compilation/*.bash; do 
  [[ -x $file ]] && $file | printline $file
done

for file in test/*.pow; do 
  ./powscript $file | printline $file
done

for file in test/interactive/*.pow; do 
  ./powscript --interactive < $file | printline $file
done

echo 'OK'
exit 0
